apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-tickets
  name: mongo-tickets
spec:
  ports:
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo-tickets
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-tickets
  name: mongo-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-tickets
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-tickets
    spec:
      containers:
        - image: mongo:5.0.14
          name: mongo-tickets
          ports:
            - containerPort: 27017
          resources: {}
          securityContext:
            runAsUser: 999
      serviceAccountName: "ad-air-sa"
      hostname: mongo-tickets
      restartPolicy: Always
status: {}
