---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    prom-service: kafka-exporter-service
  annotations:
    appdynamics.com/exporter_type: "kafka"
    appdynamics.com/kafka_cluster_name: "kafka"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9308"
spec:
  type: ClusterIP
  ports:
    - port: 9308
      name: "kexporter"
      targetPort: 9308
      protocol: TCP
  selector:
    prom-service: kafka-exporter
  clusterIP: ""
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      prom-service: kafka-exporter
  strategy: {}
  template:
    metadata:
      labels:
        prom-service: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: "danielqsj/kafka-exporter:latest"
          args:
            - --kafka.server=kafka:9092
            - --zookeeper.server=zookeeper:2181
            - --verbosity=2
          ports:
            - name: "kexporter"
              containerPort: 9308
              protocol: TCP
status: {}
