apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ticket-services
    framework: java
  name: ticket-services
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticket-services
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
      creationTimestamp: null
      labels:
        io.kompose.service: ticket-services
    spec:
      containers:
        - env:
            - name: KAFKA_LISTENER_CLASS
              value: com.java.acme.kafka.TicketServicesKafkaListener
            - name: TOPIC_LIST
              value: customer-services
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['io.kompose.service']
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: appdynamics/ad-air-java-services
          name: ticket-services
          resources: {}
      hostname: ticket-services
      restartPolicy: Always
status: {}
