---
kind: Namespace
apiVersion: v1
metadata:
  name: charles-ad-air
  labels:
    name: charles-ad-air
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ad-air-sa
  namespace: charles-ad-air
#automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "petclinic-sa" to run as anyuid.
kind: RoleBinding
metadata:
  name: ad-air-sa-rb
subjects:
# You can specify more than one "subject"
  - namespace: charles-ad-air
    kind: ServiceAccount
    name: ad-air-sa
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: system:openshift:scc:anyuid # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
