apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
spec:
  exporter:
    endpoint: http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp,logging"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4317"
      - name: OTEL_JAVAAGENT_DEBUG
        value: "true"
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4317"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.namespace=$(OTEL_POD_NAMESPACE)"
      - name: OTEL_NODEJS_DEBUG
        value: "true"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.36b0
    env:
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: "http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4318/v1/traces"
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOG_LEVEL
        value: "debug"
