apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-sessions
  name: mongo-sessions
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo-sessions
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-sessions
  name: mongo-sessions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-sessions
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-sessions
    spec:
      containers:
        - image: mongo:5.0.14
          name: mongo-sessions
          ports:
            - containerPort: 27017
          resources: {}
      hostname: mongo-sessions
      restartPolicy: Always
status: {}
