apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-services
  name: auth-services
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: auth-services
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-services
    framework: nodejs
  name: auth-services
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-services
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      creationTimestamp: null
      labels:
        io.kompose.service: auth-services
    spec:
      containers:
        - image: lincharles/ad-air-nodejs-services
          name: auth-services
          ports:
            - containerPort: 8080
          resources: {}
      hostname: auth-services
      restartPolicy: Always
status: {}
