apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ticketing-load
  name: ticketing-load
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticketing-load
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ticketing-load
    spec:
      containers:
        - env:
            - name: ENABLE_TICKETING_LOAD
              value: "1"
          image: appdynamics/ad-air-load
          name: ticketing-load
          resources: {}
      restartPolicy: Always
status: {}
